<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_portal/Desboard.Master" AutoEventWireup="true" CodeBehind="Course.aspx.cs" Inherits="University_Management_System.Admin_portal.WebForm4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div class="card mt-5">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-info shadow-info border-radius-lg pt-4 pb-3">
                <h5 class="text-white text-capitalize ps-3"><i class="fas fa-user-plus"></i> &nbsp;Add Course</h5>
              </div>
            </div>
        <%--<div class="card-header">

            <h4>
                User Lists
            </h4>
        </div>--%> 
        <div class="card-body">

            <form>
                 <div id="u_fs" class="input-group input-group-outline mb-3" runat="server">
      <asp:Label ID="lb_code" runat="server" Enabled="False" Text="Course Code" CssClass="form-label"></asp:Label>
     <asp:TextBox ID="tb_code" runat="server" CssClass="form-control"></asp:TextBox>
 </div>
                <div id="u_f" class="input-group input-group-outline mb-3" runat="server">
                     <asp:Label ID="lb_course" runat="server" Enabled="False" Text="Course Name" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="tb_course_name" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                <div class="input-group input-group-outline mb-3">
                      <%--<asp:Label ID="lb_did" runat="server" Enabled="False" Text="Department" CssClass="form-label"></asp:Label>--%>
                      <asp:DropDownList ID="ddl_did" runat="server"  CssClass="form-control"></asp:DropDownList>
                </div>
                <%--<div class="input-group input-group-outline mb-3">
                    <asp:Label ID="lb_pass0" runat="server" Enabled="False" Text="ReType Password" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="tb_re_pass" runat="server" TextMode="Password" CssClass="form-control"></asp:TextBox>
                </div>
                --%>
                                 <asp:Button ID="btn_sub" runat="server" Text="Submit" ValidationGroup="val_user" CssClass="btn btn-info" OnClick="btn_sub_Click"/>
&nbsp;
                                <asp:Button ID="btn_up" runat="server" Text="Update" ValidationGroup="val_user" CssClass="btn btn-info" OnClick="btn_up_Click"/>


            </form>
        </div>
    </div>
            <div class="card mt-5">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-info shadow-info border-radius-lg pt-4 pb-3">
                <h5 class="text-white text-capitalize ps-3"><i class="fas fa-users-cog"></i> &nbsp;view Course</h5>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <asp:GridView ID="dgv_course" class="table align-items-center mb-0" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnSelectedIndexChanged="dgv_course_SelectedIndexChanged" OnRowDeleting="dgv_course_RowDeleting">
                </asp:GridView>
                  </div>
                </div>
        
    </div>
                    
<br />
<br />
<br />
</asp:Content>
