<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_portal/Desboard.Master" AutoEventWireup="true" CodeBehind="Department.aspx.cs" Inherits="University_Management_System.Admin_portal.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
         <div class="card mt-5">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-info shadow-info border-radius-lg pt-4 pb-3">
                <h5 class="text-white text-capitalize ps-3"><i class="fas fa-user-plus"></i> &nbsp;Add Department</h5>
              </div>
            </div>
        <%--<div class="card-header">

            <h4>
                User Lists
            </h4>
        </div>--%> 
        <div class="card-body">

            <form>
                <div id="u_f" class="input-group input-group-outline mb-3" runat="server">
                     <asp:Label ID="lb_dep" runat="server" Enabled="False" Text="Departmnet Name" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="tb_dept_name" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                <div class="input-group input-group-outline mb-3">
                    <asp:Label ID="lb_stream" runat="server" Enabled="False" Text="Stream" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="tb_stream" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                <div class="input-group input-group-outline mb-3">
                    <asp:Label ID="lb_yearly_fee" runat="server" Enabled="False" Text="Yearly Fees" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="tb_yearly_fees" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                
                                 <asp:Button ID="btn_sub" runat="server" Text="Submit" ValidationGroup="val_user" CssClass="btn btn-info" OnClick="btn_sub_Click"/>
&nbsp;
                                <asp:Button ID="btn_up" runat="server" Text="Update" ValidationGroup="val_user" CssClass="btn btn-info" OnClick="btn_up_Click"/>


            </form>
        </div>
    </div>
            <div class="card mt-5">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-info shadow-info border-radius-lg pt-4 pb-3">
                <h5 class="text-white text-capitalize ps-3"><i class="fas fa-users-cog"></i> &nbsp;view Departments</h5>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <asp:GridView ID="dgv_department" class="table align-items-center mb-0" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnSelectedIndexChanged="dgv_user_SelectedIndexChanged" OnRowDeleting="dgv_user_RowDeleting">
                </asp:GridView>
                  </div>
                </div>
        
    </div>
                    
<br />
<br />
<br />
                           <%-- <table class="auto-style6" style="border: medium solid #666666; background-color: #C0C0C0; ">
                        <tr>
                            <td class="auto-style7" colspan="3" style="text-align: center">Add Department</td>
                        </tr>
                        <tr>
                            <td class="auto-style16" style="text-align: right">
                                Department</td>
                            <td class="auto-style7">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="tb_dept_name" runat="server"></asp:TextBox>
                            </td>
                            <td class="auto-style2">
                                <asp:RequiredFieldValidator ID="rvf_dept" runat="server" ControlToValidate="tb_dept_name" Display="Dynamic" ErrorMessage="*" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator>
&nbsp; </td>
                        </tr>
                        <tr>
                            <td class="auto-style16" style="text-align: right">
                                Stream</td>
                            <td class="auto-style7">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="tb_stream" runat="server"></asp:TextBox>
                            </td>
                            <td class="auto-style2">
                                <asp:RequiredFieldValidator ID="rfv_stream" runat="server" ControlToValidate="tb_stream" Display="Dynamic" ErrorMessage="*" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator>
&nbsp;&nbsp;
                                </td>
                        </tr>
                        <tr>
                            <td class="auto-style17" style="text-align: right">
                                Yearly Fees</td>
                            <td class="auto-style15">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="tb_yearly_fees" runat="server"></asp:TextBox>
                            </td>
                            <td class="auto-style1">
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" class="auto-style5" style="text-align: center">
                                <asp:Button ID="btn_sub" runat="server" Text="Submit" ValidationGroup="val_user" BackColor="#666666" ForeColor="White" Width="86px" CssClass="sub_btn" Height="35px" OnClick="btn_sub_Click"/>
&nbsp;
                                <asp:Button ID="btn_up" runat="server" Text="Update" ValidationGroup="val_user" BackColor="#666666" ForeColor="White" Width="86px" CssClass="sub_btn" Height="35px" OnClick="btn_up_Click"/>
                            </td>
                        </tr>
                    </table>
          <br>
    <br />
<br />
                    <asp:GridView ID="dgv_department" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnSelectedIndexChanged="dgv_user_SelectedIndexChanged" OnRowDeleting="dgv_user_RowDeleting">
                        <AlternatingRowStyle BackColor="White" />
                        <FooterStyle BackColor="#CCCC99" />
                        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                        <RowStyle BackColor="#F7F7DE" />
                        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#FBFBF2" />
                        <SortedAscendingHeaderStyle BackColor="#848384" />
                        <SortedDescendingCellStyle BackColor="#EAEAD3" />
                        <SortedDescendingHeaderStyle BackColor="#575357" />
                    </asp:GridView>
<br />
<br />
<br />--%>
</asp:Content>
