<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_portal/Desboard.Master" AutoEventWireup="true" CodeBehind="Fee_Structure.aspx.cs" Inherits="University_Management_System.Admin_portal.WebForm5" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <%--<link href="../css/st.css" rel="stylesheet" />--%>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
         <div class="card mt-5">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-info shadow-info border-radius-lg pt-4 pb-3">
                <h5 class="text-white text-capitalize ps-3"><i class="fas fa-user-plus"></i> &nbsp;Add Fee Structure</h5>
              </div>
            </div>
        <%--<div class="card-header">

            <h4>
                User Lists
            </h4>
        </div>--%> 
        <div class="card-body">

            <form>
                <div id="u_f" class="input-group input-group-outline mb-3" runat="server">
                     <asp:Label ID="lb_course" runat="server" Enabled="False" Text="Course Name" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="tb_course_name" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                <div class="input-group input-group-outline mb-3">
                      <%--<asp:Label ID="lb_dep" runat="server" Enabled="False" Text="Department" CssClass="form-label"></asp:Label>--%>
                      <asp:DropDownList ID="ddl_dep" runat="server"  CssClass="form-control selectpicker"></asp:DropDownList>
                </div>
               <div class="input-group input-group-outline mb-3">

                    <asp:DropDownList ID="ddl_Sem" runat="server" CssClass="form-control selectpicker">
                    <asp:ListItem>Select Sem</asp:ListItem>
                    <asp:ListItem>Odd</asp:ListItem>
                    <asp:ListItem>Even</asp:ListItem>
                        </asp:DropDownList>
                </div>
                <div id="Div1" class="input-group input-group-outline mb-3" runat="server">
                    <asp:Label ID="lb_year" runat="server" Enabled="False" Text="Year" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="txt_Year" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                <div id="Div2" class="input-group input-group-outline mb-3" runat="server">
                    <asp:Label ID="lb_feeamount" runat="server" Enabled="False" Text="Fee Amount" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="txt_Feeamount" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                                 <asp:Button ID="btn_sub" runat="server" Text="Submit" ValidationGroup="val_user" CssClass="btn btn-info" OnClick="btn_sub_Click"/>
&nbsp;
                                <asp:Button ID="btn_up" runat="server" Text="Update" ValidationGroup="val_user" CssClass="btn btn-info" OnClick="btn_up_Click"/>


            </form>
        </div>
    </div>
            <div class="card mt-5">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-info shadow-info border-radius-lg pt-4 pb-3">
                <h5 class="text-white text-capitalize ps-3"><i class="fas fa-users-cog"></i> &nbsp;view Fee Structure</h5>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <asp:GridView ID="dgv_fee_structure" class="table align-items-center mb-0" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnSelectedIndexChanged="dgv_fee_structure_SelectedIndexChanged" OnRowDeleting="dgv_fee_structure_RowDeleting">
                </asp:GridView>
                  </div>
                </div>
        
    </div>
                    
<br />
<br />
<br />
                          <%--  <table class="auto-style6" style="border: medium solid #666666; background-color: #C0C0C0; ">
                        <tr>
                            <td class="auto-style7" colspan="3" style="text-align: center">Add Fee Structure</td>
                        </tr>
                        <tr>
                            <td class="auto-style14" style="text-align: right">
                                Department</td>
                            <td class="auto-style15">
                                &nbsp; &nbsp;
                                <asp:DropDownList ID="ddl_dep" runat="server" Height="25px">
                                </asp:DropDownList>
                            </td>
                            <td class="auto-style3">
                                <asp:RequiredFieldValidator ID="rfv_dpt" runat="server" ControlToValidate="ddl_dep" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
&nbsp;&nbsp;
                                </td>
                        </tr>
                        <tr>
                            <td class="auto-style10" style="text-align: right">
                                Sem</td>
                            <td class="auto-style12">
                                &nbsp;&nbsp;&nbsp;&nbsp;<asp:DropDownList ID="ddl_Sem" runat="server" Height="24px">
                                    <asp:ListItem>--select sem--</asp:ListItem>
                                    <asp:ListItem>Odd</asp:ListItem>
                                    <asp:ListItem>Even</asp:ListItem>
                                </asp:DropDownList>
                            </td>
                            <td class="auto-style4">
                                <asp:RequiredFieldValidator ID="rfv_sem" runat="server" ControlToValidate="ddl_Sem" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1" style="text-align: right">
                                Year</td>
                            <td class="auto-style13">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="txt_Year" runat="server" TextMode="Number"></asp:TextBox>
                            </td>
                            <td class="auto-style4">
                                <asp:RequiredFieldValidator ID="rfv_sem0" runat="server" ControlToValidate="txt_Year" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1" style="text-align: right">
                                Fee Amount</td>
                            <td class="auto-style13">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="txt_Feeamount" runat="server" TextMode="Number"></asp:TextBox>
                            </td>
                            <td class="auto-style4">
                                &nbsp;</td>
                        </tr>
                        <tr>
                            <td colspan="3" class="auto-style5" style="text-align: center">
                                <asp:Button ID="btn_sub" runat="server" Text="Submit" ValidationGroup="val_user" BackColor="#666666" ForeColor="White" Width="86px" CssClass="sub_btn" Height="35px" OnClick="btn_sub_Click" OnClientClick="btn_sub_Click"/>
&nbsp;
                                <asp:Button ID="btn_up" runat="server" Text="Update" ValidationGroup="val_user" BackColor="#666666" ForeColor="White" Width="86px" CssClass="sub_btn" Height="35px" OnClick="btn_up_Click" />
                            </td>
                        </tr>
                    </table>
          <br>
    <br />
<br />
                    <asp:GridView ID="dgv_fee_structure" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnSelectedIndexChanged="dgv_fee_structure_SelectedIndexChanged" OnRowDeleting="dgv_fee_structure_RowDeleting">
                        <AlternatingRowStyle BackColor="White" />
                        <FooterStyle BackColor="#CCCC99" />
                        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                        <RowStyle BackColor="#F7F7DE" />
                        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#FBFBF2" />
                        <SortedAscendingHeaderStyle BackColor="#848384" />
                        <SortedDescendingCellStyle BackColor="#EAEAD3" />
                        <SortedDescendingHeaderStyle BackColor="#575357" />
                    </asp:GridView>
<br />
<br />
<br />--%>
</asp:Content>
