<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_portal/Desboard.Master" AutoEventWireup="true" CodeBehind="user_list.aspx.cs" Inherits="University_Management_System.Admin_portal.user_list" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="card mt-5">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-info shadow-primary border-radius-lg pt-4 pb-3">
                <h5 class="text-white text-capitalize ps-3"><i class="fas fa-user-plus"></i> &nbsp;Add User</h5>
              </div>
            </div>
        <%--<div class="card-header">

            <h4>
                User Lists
            </h4>
        </div>--%> 
        <div class="card-body">

            <form>
                <div id="u_f" class="input-group input-group-outline mb-3" runat="server">
                     <asp:Label ID="lb_user" runat="server" Enabled="False" Text="User Name " CssClass="form-label"><asp:RequiredFieldValidator ID="rvf_user" runat="server" ControlToValidate="tb_user_name" Display="Dynamic" ErrorMessage=" *" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator></asp:Label>

                    <asp:TextBox ID="tb_user_name" runat="server" CssClass="form-control"></asp:TextBox>
                   
                </div>
                 
                <div class="input-group input-group-outline mb-3">
                      <asp:Label ID="lb_pass" runat="server" Enabled="False" Text="Password" CssClass="form-label"></asp:Label>
                      <asp:TextBox ID="tb_pass" runat="server" TextMode="Password" CssClass="form-control"></asp:TextBox>
                </div>
                <div class="input-group input-group-outline mb-3">
                    <asp:Label ID="lb_pass0" runat="server" Enabled="False" Text="ReType Password" CssClass="form-label"></asp:Label>
                    <asp:TextBox ID="tb_re_pass" runat="server" TextMode="Password" CssClass="form-control"></asp:TextBox>
                </div>
                
                                 <asp:Button ID="btn_sub" runat="server" Text="Submit" ValidationGroup="val_user" CssClass="btn btn-info" OnClick="btn_sub_Click"/>
&nbsp;
                                <asp:Button ID="btn_up" runat="server" Text="Update" ValidationGroup="val_user" CssClass="btn btn-info" OnClick="btn_up_Click"/>
                

            </form>
        </div>
    </div>
    
        <div class="card mt-5">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-info shadow-primary border-radius-lg pt-4 pb-3">
                <h5 class="text-white text-capitalize ps-3"><i class="fas fa-users-cog"></i> &nbsp;view User</h5>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <asp:GridView ID="dgv_user" class="table align-items-center mb-0" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="dgv_user_SelectedIndexChanged" OnRowDeleting="dgv_user_RowDeleting">
</asp:GridView>
                  </div>
                </div>
        
    </div>
                        <%--<table class="auto-style6" style="border: medium solid #666666; background-color: #C0C0C0; ">
                        <tr>
                            <td class="auto-style7" colspan="3" style="text-align: center">Add User</td>
                        </tr>
                        <tr>
                            <td class="auto-style16" style="text-align: right">
                                <asp:Label ID="lb_user1" runat="server" Enabled="False" Text="User Name"></asp:Label>
                            </td>
                            <td class="auto-style7">
                                &nbsp;&nbsp;&nbsp;--%>
                                <%--<asp:TextBox ID="tb_user_name" runat="server"></asp:TextBox>
                            </td>
                            <td class="auto-style2">
                                <asp:RequiredFieldValidator ID="rvf_user" runat="server" ControlToValidate="tb_user_name" Display="Dynamic" ErrorMessage="*" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator>
&nbsp; </td>
                        </tr>
                        <tr>
                            <td class="auto-style16" style="text-align: right">
                                <asp:Label ID="lb_pass" runat="server" Enabled="False" Text="Password"></asp:Label>
                            </td>
                            <td class="auto-style7">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="tb_pass" runat="server" TextMode="Password"></asp:TextBox>
                            </td>
                            <td class="auto-style2">
                                <asp:RequiredFieldValidator ID="rfv_pass" runat="server" ControlToValidate="tb_pass" Display="Dynamic" ErrorMessage="*" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator>
&nbsp;&nbsp;
                                </td>
                        </tr>
                        <tr>
                            <td class="auto-style17" style="text-align: right">
                                <asp:Label ID="lb_pass0" runat="server" Enabled="False" Text="ReType Password"></asp:Label>
                            </td>
                            <td class="auto-style15">
                                &nbsp;&nbsp;&nbsp;
                                <asp:TextBox ID="tb_re_pass" runat="server" TextMode="Password"></asp:TextBox>
                            </td>
                            <td class="auto-style1">
                                <asp:RequiredFieldValidator ID="rfv_pass0" runat="server" ControlToValidate="tb_re_pass" Display="Dynamic" ErrorMessage="*" ForeColor="Red" ValidationGroup="val_user" SetFocusOnError="True"></asp:RequiredFieldValidator>
                                <br />
                                <asp:CompareValidator ID="CompareValidator1" runat="server" ControlToCompare="tb_pass" ControlToValidate="tb_re_pass" Display="Dynamic" ErrorMessage="Password Not match" ForeColor="Red" SetFocusOnError="True" ValidationGroup="val_user"></asp:CompareValidator>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" class="auto-style5" style="text-align: center">
                                <asp:Button ID="btn_sub" runat="server" Text="Submit" ValidationGroup="val_user" BackColor="#666666" ForeColor="White" Width="86px" CssClass="sub_btn" Height="35px" OnClick="btn_sub_Click"/>
&nbsp;
                                <asp:Button ID="btn_up" runat="server" Text="Update" ValidationGroup="val_user" BackColor="#666666" ForeColor="White" Width="86px" CssClass="sub_btn" Height="35px" OnClick="btn_up_Click"/>
                                <asp:Button ID="Button1" runat="server" Text="Button" OnClick="Button1_Click" />
                            </td>
                        </tr>
                    </table>--%>
          <br>
    <br />
<br />
                    
<br />
<br />
<br />
</asp:Content>
